export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';
export const SET_FOCUS = 'SET_FOCUS';
export const COPY = "COPY";
export const CHANGE_USER_NEW_DATA = "CHANGE_USER_NEW_DATA";
export const RESET_ATTENTION_COMMENTS = "RESET_ATTENTION_COMMENTS";